spring:
  profiles:
    active:
    - dev
    
---
spring:
  profiles: dev # 开发环境
  application:
    name: microservicecloud-config-yuanleigen-dev
    
---
spring:
  profiles: test # 测试环境
  application:
    name: microservicecloud-config-yuanleigen-test
    
# 注意需要使用UTF-8编码解码格式