spring:
  profiles:
    active:
    - dev
    
---
server:
  port: 8002 # 注册中心占用7001端口，冒号后面必须要有空格

spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    url: jdbc:mysql://localhost:3306/cloudDB01?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai      # 数据库名称
    username: root
    password: 123456
    
mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.yuanleigen.springcloud.entity # 所有Entity别名类所在包
  mapper-locations: # mapper映射文件所在路径
  - classpath:mybatis/mapper/**/*.xml
    
eureka:
  client:
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
      
info:
  app.name: yuanleigen.com-springcloudconfig02
      
---
server:
  port: 8002 # 注册中心占用7001端口，冒号后面必须要有空格

spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    url: jdbc:mysql://localhost:3306/cloudDB02?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai      # 数据库名称
    username: root
    password: 123456
    
mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.yuanleigen.springcloud.entity # 所有Entity别名类所在包
  mapper-locations: # mapper映射文件所在路径
  - classpath:mybatis/mapper/**/*.xml
    
eureka:
  client:
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
      
info:
  app.name: yuanleigen.com-springcloudconfig02
  company.name: www.yuanleigen.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$$